/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprojetot;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Frankyston&Nathalia
 */
public class Vendas extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public Vendas() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        
        // Metodo que faz uma ação quando clica em fechar da janela
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                new BemVindo().setVisible(true);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        btCadastraVenda = new javax.swing.JButton();
        btRemoveVenda = new javax.swing.JButton();
        btListaVenda = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SisVenda - Gerenciamento de Vendas");
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbTitulo.setText("Escolha que opção deseja fazer:");

        btCadastraVenda.setText("Cadastrar Venda");
        btCadastraVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastraVendaActionPerformed(evt);
            }
        });

        btRemoveVenda.setText("Remover Venda");
        btRemoveVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveVendaActionPerformed(evt);
            }
        });

        btListaVenda.setText("Lista Vendas");
        btListaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListaVendaActionPerformed(evt);
            }
        });

        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastraVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btRemoveVenda)
                        .addGap(18, 18, 18)
                        .addComponent(btListaVenda)
                        .addGap(18, 18, 18)
                        .addComponent(btVoltar)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastraVenda)
                    .addComponent(btRemoveVenda)
                    .addComponent(btListaVenda)
                    .addComponent(btVoltar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRemoveVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveVendaActionPerformed
        try{
            int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da venda que deseja Remover:"));

            VendaDao dao;
            try {
                dao = new VendaDao();
                dao.RemoverVenda(id);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao chamar Remover Vendas");
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Erro ao Remover Venda!");
        }
    }//GEN-LAST:event_btRemoveVendaActionPerformed

    private void btCadastraVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastraVendaActionPerformed
        new CadastroVenda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCadastraVendaActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        new BemVindo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btListaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListaVendaActionPerformed
        new ListaVenda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btListaVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastraVenda;
    private javax.swing.JButton btListaVenda;
    private javax.swing.JButton btRemoveVenda;
    private javax.swing.JButton btVoltar;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
 
}
